#!/bin/sh

BASE_URL="http://wmap.example.com/weathermap.png"

cd /var/www/mrtg/vortex
test -d weathermap/`date +%y` || mkdir -p weathermap/`date +%y`
wget $BASE_URL -O weathermap/`date +%y`/weathermap-`date +%y%m%d%H%M`.png

exit $?
