#!/bin/sh

PRG=`basename $0`

usage()
{
    echo "Usage: $PRG <ip>"
}

if test -z "$1"; then
    usage >&2
    exit 1
elif test "$1" = -h -o "$1" = --help; then
    usage
    exit 0
fi
eval `echo $1 | sed 's|^\([0-9]*\)\.\([0-9]*\)\.\([0-9]*\)\.\([0-9]*\)|byte1=\1 byte2=\2 byte3=\3 byte4=\4|'` 2>/dev/null
if test -z "$byte1" -o -z "$byte2" -o -z "$byte3" -o -z "$byte4"; then
    usage >&2
    exit 1
fi

abusix=`host -t any $byte4.$byte3.$byte2.$byte1.abuse-contacts.abusix.org | egrep -o '\w+([._-]\w)*@\w+([._-]\w+)*\.\w{2,4}'`
if test -z "$abuseix"; then
    abusix=`host -t any 0.$byte3.$byte2.$byte1.abuse-contacts.abusix.org | egrep -o '\w+([._-]\w)*@\w+([._-]\w+)*\.\w{2,4}'`
fi
if test -z "$abuseix"; then
    whois=`whois $1 | grep -i abuse | egrep -o '\w+([._-]\w)*@\w+([._-]\w+)*\.\w{2,4}' | head -1`
    if test -z "$whois"; then
	whois=`whois $byte1.$byte2.$byte3.0 | grep -i abuse | egrep -o '\w+([._-]\w)*@\w+([._-]\w+)*\.\w{2,4}' | head -1`
    fi
    if test -z "$whois"; then
	whoever=`whois $1 | egrep -o '\w+([._-]\w)*@\w+([._-]\w+)*\.\w{2,4}' | head -1`
	if test -z "$whoever"; then
	    whoever=`whois $byte1.$byte2.$byte3.0 | egrep -o '\w+([._-]\w)*@\w+([._-]\w+)*\.\w{2,4}' | head -1`
	fi
    fi
fi

for val in abuseix whois whoever
do
    eval abuse=\$$val
    if test "$abuse"; then
	echo $abuse
	exit 0
    fi
done

echo Unable to find contact for $1 >&2
exit 1
