class pki::vars {
    $ca_expire      = lookup("pki_ca_expire")
    $contact        = lookup("pki_contact")
    $domains_lookup = lookup("pki_domains_lookup")
    $key_city       = lookup("pki_key_city")
    $key_country    = lookup("pki_key_country")
    $key_expire     = lookup("pki_key_expire")
    $key_org        = lookup("pki_key_org")
    $key_province   = lookup("pki_key_province")
    $key_size       = lookup("pki_key_size")
    $listen_ports   = lookup("apache_listen_ports")
    $pki_master     = lookup("pki_master")
    $pki_public     = lookup("pki_public")
    $nocontact      = lookup("pki_nocontact")
    $ovpngw         = lookup("openvpn_gateway")
    $search_user    = lookup("openvpn_searchuser")
    $zip_pass       = lookup("zip_password")
}
