class ipfw::vars {
    $all_networks      = lookup("vlan_database", {merge => hash})
    $all_openvpns      = lookup("openvpn_database", {merge => hash})
    $local_networks    = lookup("active_vlans")
    $munin_ip          = lookup("munin_ip")
    $munin_listenaddr  = lookup("munin_node_listenaddr")
    $munin_port        = lookup("munin_port")
    $myvlan            = lookup("myvlan")
    $nagios_ip         = lookup("nagios_ip")
    $nagios_listenaddr = lookup("nagios_listenaddr")
    $nagios_port       = lookup("nagios_nrpe_port")
    $netids            = lookup("office_netids")
    $ovpn_networks     = lookup("active_openvpns")
    $snmp_ip           = lookup("snmp_ip")
    $snmp_listenaddr   = lookup("snmp_listenaddr")
}
