class samba::vars {
    $contact             = lookup("samba_contact")
    $dir_map             = lookup("samba_directory_setperms")
    $ldap_slave          = lookup("openldap_ldap_slave")
    $samba_domainname    = lookup("samba_domainname")
    $samba_domainsid     = lookup("samba_domainsid")
    $samba_binddn        = lookup("samba_bind_dn")
    $samba_bindpw        = lookup("samba_bind_passphrase")
    $samba_fsopts        = lookup("samba_nfs_opts")
    $samba_ldap_sfx      = lookup("samba_ldap_suffix")
    $samba_nfs_path      = lookup("samba_nfs_path")
    $samba_over_nfs      = lookup("samba_over_nfs")
    $samba_shares        = lookup("samba_shares")
    $samba_user_sfx      = lookup("samba_user_suffix")
    $samba_veto          = lookup("samba_veto_files")
}
