#!/bin/sh
# Mate Gabri <mate@gabri.hu>
# GPLv2

if test "$1" = autoconf; then
    echo yes
elif test "$1" = config; then
    echo 'graph_title CEPH OSDs'
    echo 'graph_category ceph'
    echo 'graph_vlabel nr'
    echo 'graph_info CEPH OSD up/down status'
    echo 'graph_scale no'
    echo 'graph_args --base 1000 -l 0'
    echo "osds.label OSDs"
    echo "up.label Up"
    echo "in.label In"
    echo "in.draw AREA"
else
    echo "osds.value $(ceph -s | grep osdmap | awk '{ print $3 }')"
    echo "up.value $(ceph -s | grep osdmap | awk '{ print $5 }')"
    echo "in.value $(ceph -s | grep osdmap | awk '{ print $7 }')"
fi

exit 0
