#!/bin/sh
# Tomas Doran <bobtfish@bobtfish.net>
# GPLv2

. $MUNIN_LIBDIR/plugins/plugin.sh

if test "$1" = config; then
    echo 'graph_title ElasticSearch translog size'
    echo 'graph_args --base 1024 -l 0'
    echo 'graph_vlabel size of translogs'
    echo 'graph_category system'
    echo 'size.label size of translog files'
    echo 'size.type GAUGE'
    echo 'number.label number of translog files'
    echo 'number.type GAUGE'
    exit 0
fi

NUMBER=`ls /var/lib/elasticsearch/*/nodes/0/indices/*/*/translog/* | wc -l`
SIZE=`du -s /var/lib/elasticsearch/*/nodes/0/indices/*/*/translog/* | awk '{sum+=$1};END{print sum}'`
echo "number.value $NUMBER"
echo "size.value $SIZE"

exit 0
