#!/bin/sh
# Stig Sandbeck Mathisen <ssm@fnord.no>
# GPLv2

client=${client:-/usr/bin/fail2ban-client}

list_jails()
{
    $client status | while read line
    do
	case $line in
	    *'Jail list:'*)
		echo $line | sed 's|[^:]*:||' | tr , '\n'
		;;
	esac
    done
}

values()
{
    list_jails | while read jail
    do
	$client status $jail | while read line
	do
	    case $line in
		*'Currently banned'*)
		    num=`echo $line | sed 's|.*:[ \t]*||g'`
		    jail=`echo $jail | sed 's|[^0-9a-zA-Z]|_|g'`
		    echo $jail.value $num
		    ;;
	    esac
	done
    done
}

config()
{
    echo 'graph_title Hosts blacklisted by fail2ban'
    echo 'graph_info This graph shows the number of host blacklisted by fail2ban'
    echo 'graph_category network'
    echo 'graph_vlabel Number of hosts'
    echo 'graph_args --base 1000 -l 0'
    echo 'graph_total total'

    list_jails | while read jail
    do
	lbl=`echo $jail | sed 's|[^0-9a-zA-Z]|_|g'`
	echo $lbl.label $jail
    done
}

autoconf()
{
    if test -e $client; then
	if test -x $client; then
	    if $client ping >/dev/null; then
		echo "yes"
	    else
		echo "no (fail2ban-server does not respond to ping)"
	    fi
	else
	    echo "no ($client is not executable)"
	fi
    else
	echo "no ($client not found)"
    fi
}

case $1 in
    config)
	config
	;;
    autoconf)
	autoconf
	;;
    *)
	values
	;;
esac

exit 0
