#!/usr/bin/env python
# Adam Comeford <acomeford@riotgames.com>
# GPLv2

import urllib2
import sys
import os
import pymongo

def getServerStatus():
    host = "127.0.0.1"
    port = 27017
    c = pymongo.MongoClient(host, port)
    return c.admin.command('serverStatus', workingSet=True)

def get():
    return getServerStatus()["indexCounters"]

def doData():
    for k,v in get().iteritems():
        print( str(k) + ".value " + str(int(v)) )

def doConfig():
    print "graph_title MongoDB btree stats"
    print "graph_args --base 1000 -l 0"
    print "graph_vlabel mb ${graph_period}"
    print "graph_category MongoDB"
    for k in get():
        print k + ".label " + k
        print k + ".min 0"
        print k + ".type COUNTER"
        print k + ".max 500000"
        print k + ".draw LINE1"

if __name__ == "__main__":
    from os import environ
    if 'HOST' in environ:
        host = environ['HOST']
    if 'PORT' in environ:
        port = environ['PORT']
    if 'USER' in environ:
        user = environ['USER']
    if 'PASSWORD' in environ:
        password = environ['PASSWORD']

if len(sys.argv) > 1 and sys.argv[1] == "config":
    doConfig()
else:
    doData()
