#!/usr/bin/env python
#-*- coding: utf-8 -*-

"""
=head1 NAME

riak_node_get_put - Plugin to monitor the number of get/put operations coordinated by this node including non-local vnodes.

=head1 AUTHOR

Hiroaki Sano

=head1 CONFIGURATION

No configuration

=head1 LICENSE

MIT License

=cut
"""

import sys
import requests
import os

host = os.getenv('riak_host','127.0.0.1')
port = os.getenv('riak_port',8098)
path = os.getenv('riak_path','stats')
proto = os.getenv('riak_proto','http')
basic = os.getenv('riak_basic',False)

def autoconf():
    pass

def get_stats():
    if basic != False:
        r = requests.get("{}://{}@{}:{}/{}".format(proto,basic,host,port,path), verify=False)
    else:
        r = requests.get("{}://{}:{}/{}".format(proto,host,port,path))
    return r.json()

def config():
    print ('graph_title Riak node_gets/puts')
    print ('graph_args --base 1000 -l 0')
    print ('graph_vlabel operations/second')
    print ('graph_category Riak')
    print ('graph_period second')
    print ('graph_info This graph shows the number of Riak get/put operations')

    print ('node_gets.label node gets')
    print ('node_gets.type DERIVE')
    print ('node_gets.max 1000000')
    print ('node_gets.min 0')
    print ('node_gets.info The number of get operations')

    print ('node_puts.label node puts')
    print ('node_puts.type DERIVE')
    print ('node_puts.max 1000000')
    print ('node_puts.min 0')
    print ('node_puts.info The number of put operations')


def main():
    if len(sys.argv) > 1:
        command = sys.argv[1]
    else:
        command = ''

    if command == 'autoconf':
        autoconf()
    elif command == 'config':
        config()
    else:
        ret = get_stats()
        print ('node_gets.value %s') % ret['node_gets_total']
        print ('node_puts.value %s') % ret['node_puts_total']

if __name__ == '__main__':
    main()
