#!/usr/bin/env python
#-*- coding: utf-8 -*-

"""
=head1 NAME

riak_erlang_processes - Plugin to monitor the number of Erlang processes.

=head1 AUTHOR

Hiroaki Sano

=head1 CONFIGURATION

No configuration

=head1 LICENSE

MIT License

=cut
"""

import sys
import requests
import os

host = os.getenv('riak_host','127.0.0.1')
port = os.getenv('riak_port',8098)
path = os.getenv('riak_path','stats')
proto = os.getenv('riak_proto','http')
basic = os.getenv('riak_basic',False)

def autoconf():
    pass

def get_stats():
    if basic != False:
        r = requests.get("{}://{}@{}:{}/{}".format(proto,basic,host,port,path), verify=False)
    else:
        r = requests.get("{}://{}:{}/{}".format(proto,host,port,path))
    return r.json()

def config():
    print ('graph_title Erlang processes')
    print ('graph_args --base 1000 -l 0')
    print ('graph_vlabel count')
    print ('graph_category Riak')
    print ('graph_period second')
    print ('graph_info This graph shows the number of Erlang processes')

    print ('erlang_processes.label Erlang processes')
    print ('erlang_processes.type GAUGE')
    print ('erlang_processes.max 1000000')
    print ('erlang_processes.min 0')
    print ('erlang_processes.info The number of Erlang processes')

def main():
    if len(sys.argv) > 1:
        command = sys.argv[1]
    else:
        command = ''

    if command == 'autoconf':
        autoconf()
    elif command == 'config':
        config()
    else:
        ret = get_stats()
        print ('erlang_processes.value %s') % ret['sys_process_count']

if __name__ == '__main__':
    main()
