#!/usr/bin/env python
#-*- coding: utf-8 -*-

"""
=head1 NAME

riak_coord_redirs - Plugin to monitor the number of requests this node has redirected to other node.

=head1 AUTHOR

Hiroaki Sano

=head1 CONFIGURATION

No configuration

=head1 LICENSE

MIT License

=cut
"""

import sys
import requests
import os

ca = os.getenv('riak_ca','False')
host = os.getenv('riak_host','127.0.0.1')
port = os.getenv('riak_port',8098)
path = os.getenv('riak_path','stats')
proto = os.getenv('riak_proto','http')
basic = os.getenv('riak_basic',False)

def autoconf():
    pass

def get_stats():
    if basic != False:
        r = requests.get("{}://{}@{}:{}/{}".format(proto,basic,host,port,path), verify=ca)
    else:
        r = requests.get("{}://{}:{}/{}".format(proto,host,port,path), verify=ca)
    return r.json()

def config():
    print ('graph_title Riak redirect')
    print ('graph_args --base 1000 -l 0')
    print ('graph_vlabel redirect/second')
    print ('graph_category Riak')
    print ('graph_period second')
    print ('graph_info This graph shows the number of requests this node has redirected to other node')

    print ('coord_redirs.label read repair')
    print ('coord_redirs.type DERIVE')
    print ('coord_redirs.max 1000000')
    print ('coord_redirs.min 0')
    print ('coord_redirs.info The number of requests this node has redirected to other node')

def main():
    if len(sys.argv) > 1:
        command = sys.argv[1]
    else:
        command = ''

    if command == 'autoconf':
        autoconf()
    elif command == 'config':
        config()
    else:
        ret = get_stats()
        print ('coord_redirs.value %s') % ret['coord_redirs_total']

if __name__ == '__main__':
    main()
