#!/bin/sh

OFFSET=/var/lib/munin/plugin-state/$(basename $0).offset
LOGFILE=/var/log/spamassassin/spamd.log

if test x$1 = xconfig; then
    echo graph_title SpamAssassin scores
    echo graph_args --base 1000 -l 0
    echo graph_category SpamAssassin
    echo graph_vlabel score
    echo maximum.label Maximum score
    echo minimum.label Minimum score
    echo average.label Average score
else
    logtail $LOGFILE $OFFSET | grep "spamd: result: " | \
	sed 's/.*result:...\(.*\) -.*/\1/' | \
	    (
		count=0
		total=0
		maximum=0
		minimum=1000000
		while read score
		do
		    total=$(expr $total + $score)
		    count=$(expr $count + 1)
		    if test $score -gt $maximum; then
			maximum=$score
		    fi
		    if test $score -lt $minimum; then
			minimum=$score
		    fi
		done

		average=0
		if test $count -gt 0; then
		    average=$(echo $total / $count | bc -l)
		fi
		if test $minimum -eq 1000000; then
		    minimum=0
		fi

		echo average.value $average
		echo maximum.value $maximum
		echo minimum.value $minimum
	    )
fi

exit 0
