#!/bin/sh

OFFSET=/var/lib/munin/plugin-state/$(basename $0).offset
LOGFILE=/var/log/spamassassin/spamd.log

if test x$1 = xconfig; then
    echo graph_title SpamAssassin stats
    echo graph_args --base 1000 -l 0
    echo graph_category SpamAssassin
    echo graph_vlabel mails
    echo spam.label Spam
    echo ham.label Ham
else
    logtail $LOGFILE $OFFSET | grep "spamd: result: " | \
	sed 's/.*result:.\(.\).* -.*/\1/' |	\
	    (
		count_spam=0
		count_ham=0
		while read stat
		do
		    if test $stat = Y; then
			count_spam=$(expr $count_spam + 1)
		    fi
		    if test $stat = .; then
			count_ham=$(expr $count_ham + 1)
		    fi
		done

		echo spam.value $count_spam
		echo ham.value $count_ham
	    )
fi

exit 0
