class openvpn::vars {
    $ad_ip                   = lookup("ad_ip")
    $all_openvpns            = lookup("openvpn_database")
    $contact_alerts          = lookup("contact_alerts")
    $contact_alerts_openvpn  = lookup("contact_alerts_openvpn")
    $dns_ip                  = lookup("dns_ip")
    $dns_push                = lookup("dns_push")
    $ldap_slave              = lookup("openldap_ldap_slave")
    $munin_monitored         = lookup("openvpn_munin")
    $munin_probes            = lookup("openvpn_munin_probes")
    $netids                  = lookup("office_netids")
    $netmask_map             = lookup("netmask_correspondance")
    $office_netid            = $netids[$domain]
    $openvpn_auth_source     = lookup("openvpn_auth_source")
    $openvpn_base_suffix     = lookup("openldap_ldap_suffix")
    $openvpn_conf_dir        = lookup("openvpn_conf_dir")
    $openvpn_default_filter  = lookup("openvpn_default_filter")
    $openvpn_keepalive       = lookup("openvpn_keepalive")
    $openvpn_ldap_passphrase = lookup("openvpn_ldap_passphrase")
    $openvpn_mute            = lookup("openvpn_mute")
    $openvpn_push_default    = lookup("openvpn_push_default")
    $openvpn_push_networks   = lookup("openvpn_push_networks")
    $openvpn_searchuser      = lookup("openvpn_searchuser")
    $openvpn_script_security = lookup("openvpn_script_security")
    $openvpn_verbosity       = lookup("openvpn_verbosity")
    $ovpn_networks           = lookup("active_openvpns")
    $rotate                  = lookup("openvpn_rotate")
    $rsyslog_conf_dir        = lookup("rsyslog_conf_dir")
    $rsyslog_service_name    = lookup("rsyslog_service_name")
    $rsyslog_version         = lookup("rsyslog_version")
    $runtime_group           = lookup("openvpn_runtime_group")
    $runtime_homedir         = lookup("openvpn_runtime_homedir")
    $runtime_shell           = lookup("openvpn_runtime_shell")
    $runtime_user            = lookup("openvpn_runtime_user")
    $with_collectd           = lookup("openvpn_collectd")

    if ($contact_alerts_openvpn) {
	$alerts = $contact_alerts_openvpn
    } else {
	$alerts = $contact_alerts
    }
}
