#!/bin/sh

PRG=`basename $0`
OK=0
WARNING=1
CRITICAL=2
UNKNOWN=3

us=`/sbin/ifconfig carp1 | awk '/MASTER/{print $4}'`
PATH="/usr/local/sbin:/usr/sbin:/sbin:$PATH"
export PATH
ret=OK
str=
if ! ps ax | awk '/bgp[d]: /{print $6" "$7}' | grep 'parent'; then
    ret=CRITICAL
    str=" - no root process"
elif ! ps ax | awk '/bgp[d]: /{print $6" "$7}' | grep 'route'; then
    ret=CRITICAL
    str=" - no RDE engine"
elif ! ps ax | awk '/bgp[d]: /{print $6" "$7}' | grep 'session'; then
    ret=WARNING
    str=" - no BGP session engine"
elif ! test -S /var/run/bgpd.sock; then
    ret=CRITICAL
    str=" - no socket"
fi >/dev/null 2>&1
cpl=$(sudo bgpctl show 2>/dev/null | grep -v '^Neighbor' | sed 's|  .*||g' | \
      while read remote
      do
	  state=`sudo bgpctl show nei "$remote" | grep 'BGP state' | sed 's|^.*state = \([^, $]*\).*|\1|g'`
	  test "$state" = Established && continue
	  str="$str - $remote is $state"
      done)
test "$ret" = OK -a "$cpl" && ret=WARNING
str="$str$cpl"

echo "$ret$str"
eval ret=\$$ret
exit $ret
