#!/bin/sh

PRG=`basename $0`
OK=0
WARNING=1
CRITICAL=2
UNKNOWN=3
res=UNKNOWN

  OID_MODEL=".1.3.6.1.4.1.6876.1.1"
OID_VERSION=".1.3.6.1.4.1.6876.1.2"

while getopts H:C:t: OPT
do
    case "$OPT" in
	H) target="$OPTARG"	;;
	C) community="$OPTARG"	;;
	t) query="$OPTARG"	;;
	*)
	    exit $UNKNOWN
	    ;;
    esac
done

if test $query = version; then
    res=`snmpwalk -t 2 -r 2 -v 1 -c $community -Ovq $target "$OID_VERSION"`
    test "$res" && ret=OK || res=unknown
    msg=" $res"
elif test $query = model; then
    res=`snmpwalk -t 2 -r 2 -v 1 -c $community -Ovq $target "$OID_MODEL"`
    test "$res" && ret=OK || res=unknown
    msg=" $res"
fi

echo $ret$msg
eval ret=\$$ret
exit $ret
