#!/bin/sh

PRG=`basename $0`
OK=0
WARNING=1
CRITICAL=2
UNKNOWN=3

TMPFILE=/tmp/.chkhpraid.$$

if ! test "$1"; then
    ret=UNKNOWN
    msg=" - need to query for a specific device"
    perfdata=" | 0"
else
    ret=CRITICAL
    msg=" - hardware RAID failure"
    prefdata=" | 0"
    sudo cciss_vol_status $1 >$TMPFILE
    if test -s "$TMPFILE"; then
	if grep 'status: OK' $TMPFILE >/dev/null; then
	    ret=OK
	    msg=
	    perfdata=" | 1"
	fi
    fi
    rm -f $TMPFILE
fi

echo "$PRG $ret$msg$perfdata"
eval ret=\$$ret
exit $ret
