#!/bin/sh
# check_kube_quotas - watch for Kubernetes & OpenShift quotas usage
# 20180820 - smoro@redhat.com

PRG=`basename $0`
OK=0
WARNING=1
CRITICAL=2
UNKNOWN=3
KUBE_ENDPOINT=
KUBE_TOKEN=
KUBE_CONFIG=$HOME/.kube/config
CHECK_CLUSTER=OpenShift
TMPFILE=/tmp/$PRG.$$
CRIT_THRESHOLD=2
WARN_THRESHOLD=1
ENV=all
ZONE_SELECTOR=
msg="all file"
perfdata=0
ret=OK

bytesconv()
{
    if test "$1" = 0; then
	echo 0
	return
    fi
    idx=1
    res=
    for u in K M G T P
    do
	if echo "$1" | grep -E "${u}i*" >/dev/null; then
	    res=$(echo $1 | sed "s|$u.*||g")
	    break
	fi
	idx=$(expr $idx + 1)
    done
    if test "$res"; then
	if echo "$1" | grep i >/dev/null; then
	    factor=1024
	else
	    factor=1000
	fi
	while test "$idx" -gt 1
	do
	    res=$(expr $res '*' $factor)
	    idx=$(expr $idx - 1)
	done
	echo "$res"
    else
	echo "$1"
    fi
}

while test "$1"
do
    case "$1" in
	-e|--endpoint)
	    if test "$2"; then
		KUBE_ENDPOINT="$2"
	    else
		echo Missing endpoint argument >&2
	    fi
	    shift
	    ;;
	-c|--critical)
	    if test "$2" -ge 0 >/dev/null 2>&1; then
		CRIT_THRESHOLD=$2
	    else
		echo Invalid critical threshold >&2
	    fi
	    shift
	    ;;
	-k|--kubeconfig)
	    if test -r "$2"; then
		KUBE_CONFIG="$2"
	    else
		echo "Could not read kubeconfig $2" >&2
	    fi
	    shift
	    ;;
	-o|--cluster)
	    if test "$2"; then
		CHECK_CLUSTER="$2"
		shift
	    else
		echo Missing cluster argument >&2
	    fi
	    ;;
	-s|--selector)
	    if echo "$2" | grep = >/dev/null; then
		ZONE_SELECTOR="--selector=$2"
	    elif test "$2"; then
		ZONE_SELECTOR="--selector=$2=true"
	    fi
	    if test "$ZONE_SELECTOR"; then
		ENV=$2
		shift
	    else
		echo Missing namespaces selector >&2
	    fi
	    ;;
	-t|--token)
	    if test "$2"; then
		KUBE_TOKEN="$2"
		shift
	    else
		echo Missing token argument >&2
	    fi
	    ;;
	-w|--warning)
	    if test "$2" -ge 0 >/dev/null 2>&1; then
		WARN_THRESHOLD=$2
	    else
		echo Invalid warning threshold >&2
	    fi
	    shift
	    ;;
	*)
	    echo "Invalid argument $1" >&2
	    ;;
    esac
    shift
done

getClusterConfig()
{
    awk "BEG{ pick = 0; }{
        if (\$0 == \"[$CHECK_CLUSTER]\") {
	    pick = 1;
	} else {
	    if (\$0 ~ /^\[.*\]/) {
		pick = 0;
	    } else {
		if (pick == 1) { print \$0; }
	    }
	}
    }" /etc/nagios/k8s.cfg
}

if test -s /etc/nagios/k8s.cfg -a -z "$KUBE_TOKEN"; then
    KUBE_TOKEN=$(getClusterConfig | awk '/^token/{print $3;exit;}')
    KUBE_ENDPOINT=$(getClusterConfig | awk '/^endpoint/{print $3;exit;}')
fi
if ! which oc >/dev/null 2>&1; then
    if ! which kubectl >/dev/null 2>&1; then
	echo UNKNOWN: missing oc and kubectl binaries
	exit $UNKNOWN
    fi
    KUBE_COMMAND=kubectl
else
    KUBE_COMMAND=oc
fi
if test "$KUBE_TOKEN" -a "$KUBE_ENDPOINT"; then
    if ! $KUBE_COMMAND --insecure-skip-tls-verify "--token=$KUBE_TOKEN" "--server=$KUBE_ENDPOINT" version >/dev/null 2>&1; then
	echo UNKNOWN: invalid token querying Kubernetes API
	exit $UNKNOWN
    fi
    AUTH_STR="--insecure-skip-tls-verify --token=$KUBE_TOKEN --server=$KUBE_ENDPOINT"
elif ! test -s $HOME/.kube/config; then
    echo UNKNOWN: missing Kubernetes configuration
    exit $UNKNOWN
elif ! $KUBE_COMMAND "--kubeconfig=$KUBE_CONFIG" version >/dev/null 2>&1; then
    echo UNKNOWN: $KUBE_COMMAND client not logged in, nor able to log in
    exit $UNKNOWN
else
    AUTH_STR="--kubeconfig=$KUBE_CONFIG"
fi
if test "$CRIT_THRESHOLD" -le "$WARN_THRESHOLD"; then
    echo notice: threshold looks incoherent >&2
fi

CHECK_NS=`$KUBE_COMMAND $AUTH_STR get ns $ZONE_SELECTOR 2>/dev/null | awk 'NR>1{print $1}'`
for ns in $CHECK_NS
do
    for qname in `$KUBE_COMMAND $AUTH_STR get quota -n $ns 2>/dev/null | awk 'NR>1{print $1}'`
    do
	$KUBE_COMMAND $AUTH_STR describe quota -n $ns $qname | grep -vE '^((Name(|space)):|Resource|--)' | \
	    while read what used total
	    do
		if echo "$what" | grep -E '(storage|memory)' >/dev/null; then
		    used=$(bytesconv $used)
		    total=$(bytesconv $total)
		elif echo "$what" | grep cpu; then
		    if ! echo "$used" | grep m; then
			used=${used}000
		    else
			used=$(echo $used | sed 's|m||')
		    fi
		    if ! echo "$total" | grep m; then
			total=${total}000
		    else
			total=$(echo $total | sed 's|m||')
		    fi
		fi >/dev/null
		if ! test "$used" -ge 0 -a "$total" -ge 0 >/dev/null 2>&1; then
		    echo "failed to parse quota $ns/$what/$used/$total" >&2
		elif test `expr "$total" '*' 80 / 100` -le "$used"; then
		    echo "$ns/$qname/$what:$used/$total" >>$TMPFILE
		fi
	    done
    done
done

if test -s $TMPFILE; then
    perfdata=`awk 'END{print NR}' $TMPFILE`
    msg="namespaces `cat $TMPFILE | tr '\n' ',' | sed 's|,$||'`"
    if test "0$perfdata" -ge "0$CRIT_THRESHOLD"; then
	ret=CRITICAL
    elif test "0$perfdata" -ge "0$WARN_THRESHOLD"; then
	ret=WARNING
    fi
fi
rm -f $TMPFILE

echo "KUBE-Quotas-$ENV $ret: $msg | $perfdata"
eval ret=\$$ret
exit $ret
