#!/bin/sh
# check_oom - watch syslog messages
# 20180427 - smoro@redhat.com

PRG=`basename $0`
OK=0
WARNING=1
CRITICAL=2
UNKNOWN=3
CRIT_THRESHOLD=5
WARN_THRESHOLD=1
ret=OK
perfdata=0

while test "$1"
do
    case "$1" in
	-c|--critical)
	    if test "$2" -ge 0 >/dev/null 2>&1; then
		CRIT_THRESHOLD=$2
	    else
		echo Invalid critical threshold >&2
	    fi
	    shift
	    ;;
	-w|--warning)
	    if test "$2" -ge 0 >/dev/null 2>&1; then
		WARN_THRESHOLD=$2
	    else
		echo Invalid warning threshold >&2
	    fi
	    shift
	    ;;
	*)
	    echo "Invalid argument $1" >&2
	    ;;
    esac
    shift
done
if test "$CRIT_THRESHOLD" -le "$WARN_THRESHOLD"; then
    echo notice: threshold looks incoherent >&2
fi

if ps ax 2>/dev/null | grep rsyslog >/dev/null; then
    MATCH=`date "+%b %d"`
    msg=`awk "/^$MATCH .*out of memory: Kill/" /var/log/messages | sed 's|^\([A-Za-z]* [0-9]* [0-9:\.]*\) .* Kill process [0-9]* (\([^)]*\).*|\2 on \1|'`
else
    msg=`journalctl --no-pager --since "1 day ago" | awk "/.*out of memory: Kill/" | sed 's|^\([A-Za-z]* [0-9]* [0-9:\.]*\) .* Kill process [0-9]* (\([^)]*\).*|\2 on \1|'`
fi

if test "$msg"; then
    perfdata=`echo "$msg" | awk 'END{print NR}'`
    if test "0$perfdata" -ge $CRIT_THRESHOLD >/dev/null 2>&1; then
	ret=CRITICAL
    elif test "0$perfdata" -ge $WARN_THRESHOLD >/dev/null 2>&1; then
	ret=WARNING
    fi
    msg="`echo "$msg" | tr '\n' ',' | sed 's|,$||'`"
else
    msg="Nothing to report"
fi

echo "OOM $ret: $msg | $perfdata"
eval ret=\$$ret
exit $ret
