#!/usr/bin/env python

# Relies on /etc/nagios/openshift.cfg querying some cluster

# Define endpoints such as:
#[Prod]
#endpoint = https://openshift.example.com:8443
#token    = abcdef
#[Sandbox]
#endpoint = https://openshift.demo.local:8443
#token    = ghijkl

# Create your token against some OpenShift cluster using:
#oc create -n monitoring-project sa monitoring-sa
#oc adm policy add-cluster-role-to-user cluster-reader system:serviceaccount:monitoring-project:monitoring-sa
#oc describe secret -n monitoring-project monitoring-sa-token-xxx

import ConfigParser
import getopt
import re
import requests
import sys
import urllib
import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

try:
    opts, args = getopt.getopt(sys.argv[1:], "c:s:o:e:t:w:", [ "selector", "critical", "cluster", "endpoint", "token", "warning" ])
except getopt.GetoptError as err:
    print(err)
    quit(3)

clusterid = 'OpenShift'
msg       = 'Nothing to report'
nodesel   = False
endpoint  = False
token     = False
crit      = 2
warn      = 1

for o, v in opts:
    if o in ( '--selector', '-s' ):
	if v in ( 'dev', 'stage', 'mgmt', 'prod' ):
            nodesel = urllib.urlencode({ 'labelSelector': 'environment=' + v })
	else:
            nodesel = urllib.urlencode({ 'labelSelector': v })
    elif o in ( '--critical', '-c' ):
	crit = v
    elif o in ( '--cluster', '-o' ):
	clusterid = v
    elif o in ( '--endpoint', '-e' ):
	endpoint = v
    elif o in ( '--token', '-t' ):
	token = v
    elif o in ( '--warning', '-w' ):
	warn = v
    else:
	assert False, "unhandled option"

config = ConfigParser.ConfigParser()
try:
    config.readfp(open(r'/etc/nagios/openshift.cfg'))
    try:
	if endpoint == False:
	    endpoint = config.get(clusterid, 'endpoint')
	if token == False:
	    token    = config.get(clusterid, 'token')
    except ConfigParser.NoOptionError:
	if token == False or endpoint == False:
	    print "UNKNOWN: missing key in cluster " + clusterid + " in /etc/nagios/openshift.cfg"
	    quit(3)
    except ConfigParser.NoSectionError:
	if token == False or endpoint == False:
	    print "UNKNOWN: could not find cluster " + clusterid + " in /etc/nagios/openshift.cfg"
	    quit(3)
except IOError:
    if token == False or endpoint == False:
	print "UNKNOWN: uninitialized endpoint - please set yours in /etc/nagios/openshift.cfg"
	quit(3)

if nodesel == False:
    url = endpoint + '/api/v1/nodes'
else:
    url = endpoint + '/api/v1/nodes?' + nodesel
headers = { "Authorization": "Bearer " + token }
req     = requests.get(url, headers=headers, verify=False)
data    = req.json()
ingress = []

try:
    if data['code'] == 401:
	print "UNKNOWN: failed querying OpenShift API - denied"
	quit(3)
    elif data['code'] != 200:
	print "UNKNOWN: unexpected code received from OpenShift API - " + data['code']
	quit(3)
except KeyError:
    pass

try:
    if len(data['items']) <= 0:
	print "UNKNOWN: empty response received from OpenShift API"
	quit(3)
except KeyError:
    print "UNKNOWN: no items returned from OpenShift API"
    quit(3)

for i in data['items']:
    try:
	if i['metadata']['labels']['node-role.kubernetes.io/ingress']:
	    ingress.append(i['metadata']['name'])
	    for j in i['status']['conditions']:
		if j['type'] == 'Ready':
		    if j['status'] != 'True':
			print "CRITICAL: node " + i['metadata']['name'] + " is down"
			quit(2)
    except KeyError:
	pass #ignoring non-ingress nodes

url = endpoint + '/api/v1/pods'
req = requests.get(url, headers=headers, verify=False)

patternRouter = re.compile('^router-([0-9]+)-([a-z0-9]+)$')
hasRouter     = []

def isOK(podStatus):
    try:
	if podStatus['containerStatuses'][0]['ready'] == True:
	    for cond in podStatus['conditions']:
		if cond['type'] == 'Ready':
		    if cond['status'] == 'True':
			return True
	return False
    except KeyError:
	return False
    except ValueError:
	return False
   
patternRouterNS = re.compile('^(tcp|)router-.*$')
data = req.json()
for i in data['items']:
    try:
	for j in ingress:
		if i['spec']['nodeName'] == j:
		    if patternRouterNS.match(i['metadata']['namespace'])
			if patternRouter.match(i['metadata']['name']):
			    if not isOK(i['status']):
				hasRouter.append(j)
    except KeyError:
	pass

if len(hasRouter) >= crit:
    msg = "CRITCAL: routers missing " + ", ".join(hasRouters)
    code = 2
if len(hasRouter) >= warn:
    msg = "WARNING: routers missing " + ", ".join(hasRouters)
    code = 1
else:
    msg = "OK: OpenShift Ingress services are UP"
    code = 0

print msg
quit(code)
