#!/bin/sh

PRG=`basename $0`
OK=0
WARNING=1
CRITICAL=2
UNKNOWN=3

if test "$1" = "-c" -a -r "$2"; then
    config=$2
else
    config=/etc/sickbeard/config.ini
fi

if test -r $config; then
    sbport=`awk -F= '/^[ 	]*web_port[ 	]*=/{print $2}' $config | sed 's|[ \t]*||g'`
fi
test -z "$sbport" && sbport=8082

if ! ps ax | grep -i ' S[i]ckBeard.py .*--daemon' >/dev/null; then
    ret=CRITICAL
    msg=" - sickbeard not running"
    perfdata=" | 0"
elif ! netstat -plant | grep ":$sbport[ 	].*LISTEN" >/dev/null; then
    ret=CRITICAL
    msg=" - sickbeard not listening on $sbport"
    prefdata=" | 0"
else
    ret=OK
    perfdata=" | 1"
fi

echo "$PRG $ret$msg$perfdata"
eval ret=\$$ret
exit $ret
