#!/usr/bin/env python
# check_kube_master - watch Kubernetes Master services
# 20200531 - smoro@redhat.com

# python 2 & 3 capable
# Relies on /etc/nagios/k8s.cfg querying some cluster
# Define endpoints such as:
#[Prod]
#endpoint = https://openshift.example.com:8443
#token    = abcdef
#[Ops]
#endpoint = https://kubernetes.demo.local:6443
#token    = ghijkl

import re
import requests
import sys

from requests.packages.urllib3.exceptions import InsecureRequestWarning
requests.packages.urllib3.disable_warnings(InsecureRequestWarning)

if len(sys.argv) >= 2:
    clusterid = sys.argv[1]
else:
    clusterid = 'OpenShift'

try:
    #python2
    import ConfigParser
    config = ConfigParser.ConfigParser()
except ModuleNotFoundError:
    #python3
    import configparser
    config = configparser.ConfigParser()

try:
    config.readfp(open(r'/etc/nagios/k8s.cfg'))
    try:
        endpoint = config.get(clusterid, 'endpoint')
        token    = config.get(clusterid, 'token')
    except (ConfigParser.NoOptionError, configparser.NoOptionError):
        print("UNKNOWN: missing key in cluster " + clusterid + " in /etc/nagios/k8s.cfg")
        quit(3)
    except (ConfigParser.NoSectionError, configparser.NoSectionError):
        print("UNKNOWN: could not find cluster " + clusterid + " in /etc/nagios/k8s.cfg")
        quit(3)
except IOError:
    print("UNKNOWN: unitilalized endpoint - please set yours in /etc/nagios/k8s.cfg")
    quit(3)

headers = {"Authorization": "Bearer " + token}
url     = endpoint + '/api/v1/nodes'
req     = requests.get(url, headers=headers, verify=False)
data    = req.json()
masters = []

try:
    if data['code'] == 401:
        print("UNKNOWN: failed querying OpenShift API - denied")
        quit(3)
    elif data['code'] != 200:
        print("UNKNOWN: unexpected code received from OpenShift API - " + data['code'])
        quit(3)
except KeyError:
    pass

try:
    if len(data['items']) <= 0:
        print("UNKNOWN: empty response received from OpenShift API")
        quit(3)
except KeyError:
    print("UNKNOWN: no items returned from OpenShift API")
    quit(3)

for i in data['items']:
    try:
        if i['metadata']['labels']['node-role.kubernetes.io/master']:
            masters.append(i['metadata']['name'])
            for j in i['status']['conditions']:
                if j['type'] == 'Ready':
                    if j['status'] != 'True':
                        print("CRITICAL: node " + i['metadata']['name'] + " is down")
                        quit(2)
    except KeyError:
        pass #ignoring non-master nodes

url  = endpoint + '/api/v1/pods'
req  = requests.get(url, headers=headers, verify=False)

patternApi        = re.compile('^kube-apiserver-([a-z0-9-]+)$')
patternController = re.compile('^kube-controller-manager-([a-z0-9-]+)$')
patternProxy      = re.compile('^kube-proxy-([a-z0-9-]+)$')
patternScheduler  = re.compile('^kube-scheduler-([a-z0-9-]+)$')

hasApi            = []
hasController     = []
hasProxy          = []
hasScheduler      = []

def isOK(podStatus):
    try:
        if podStatus['containerStatuses'][0]['ready'] == True:
            for cond in podStatus['conditions']:
                if cond['type'] == 'Ready':
                    if cond['status'] == 'True':
                        return True
        return False
    except KeyError:
        return False
    except ValueError:
        return False
   
data = req.json()
for i in data['items']:
    try:
        for j in masters:
                if i['spec']['nodeName'] == j:
                    if i['metadata']['namespace'] == 'kube-system':
                        if patternApi(i['metadata']['name'] ):
                            if not isOK(i['status']):
                                hasApi.append(j)
                        elif patternController(i['metadata']['name'] ):
                            if not isOK(i['status']):
                                hasController.append(j)
                        elif patternProxy(i['metadata']['name'] ):
                            if not isOK(i['status']):
                                hasProxy.append(j)
                        elif patternScheduler(i['metadata']['name'] ):
                            if not isOK(i['status']):
                                hasScheduler.append(j)
    except KeyError:
        pass

code = 2
if len(hasApi) > 0:
    msg = "CRITICAL: API missing " + ' '.join(hasApi)
elif len(hasController) > 0:
    msg = "CRITICAL: Controllers missing " + ' '.join(hasController)
elif len(hasScheduler) > 0:
    msg = "CRITICAL: Schedulers missing " + ' '.join(hasScheduler)
elif len(hasProxy) > 0:
    msg = "WARNING: Proxies missing " + ' '.join(hasProxy)
    code = 1
else:
    msg = "OK: Kubernetes Core services are UP"
    code = 0

print(msg)
quit(code)
