#!/bin/sh

PRG=`basename $0`
OK=0
WARNING=1
CRITICAL=2
UNKNOWN=3

if test "$1"; then
    MASTER_ENDPOINT="$1"
else
    MASTER_ENDPOINT=openshift.example.com:8443
fi
if echo "$MASTER_ENDPOINT" | grep : >/dev/null; then
    MASTER_PORT=`echo $MASTER_ENDPOINT | cut -d: -f2`
else
    MASTER_PORT=443
fi
if ! systemctl is-active atomic-openshift-node; then
    ret=CRITICAL
    msg=": node not running"
elif ! systemctl is-active openvswitch; then
    ret=CRITICAL
    msg=": openvswitch not running"
elif ! /usr/lib64/nagios/plugins/check_http $MASTER_ENDPOINT -u https://$MASTER_ENDPOINT/healthz -S -s ok; then
    ret=WARNING
    msg=": master-api is unhealthy"
elif ! /usr/lib64/nagios/plugins/check_http docker-registry.default.svc.cluster.local -u https://docker-registry.default.svc.cluster.local:5000/healthz -p5000 -S -e 200; then
    ret=WARNING
    msg=": internal registry is unhealthy"
else
    ret=OK
    msg=": Nothing to report"
fi >/dev/null 2>&1

echo "OC-node $ret$msg"
eval ret=\$$ret
exit $ret
