#!/bin/sh
# check_fluentd - watch for Fluentd buffers
# 20181030 - smoro@redhat.com

PRG=`basename $0`
OK=0
WARNING=1
CRITICAL=2
UNKNOWN=3

FLUENTD_BUFFERS=${FLUENTD_BUFFERS:-/var/lib/fluentd}

FILES_CRIT_THRESHOLDS=5
FILES_WARN_THRESHOLDS=1
FILES_MINUTES_THRESHOLDS=10

ret=OK
msg=" - all fine"
perfdata=$(find $FLUENTD_BUFFERS -mmin +$FILES_MINUTES_THRESHOLDS -type f -name 'buffer-output-es-config.output_tag*' | wc -l)

if test "$perfdata" -ge $FILES_CRIT_THRESHOLDS; then
    ret=CRITICAL
    msg=" - buffers piling up"
elif test "$perfdata" -ge $FILES_WARN_THRESHOLDS; then
    ret=WARNING
    msg=" - buffers accumulating"
fi

echo "Fluentd Buffers $ret$msg| $perfdata"
eval ret=\$$ret
exit $ret
