class collectd::vars {
    $interval       = lookup("collectd_interval")
    $cache_flush    = lookup("collectd_cache_flush")
    $conf_dir       = lookup("collectd_conf_dir")
    $log_dir        = lookup("collectd_log_dir")
    $graphite       = lookup("collectd_graphite")
    $plugins        = lookup("collectd_default_plugins")
    $readthreads    = lookup("collectd_readthreads")
    $run_dir        = lookup("collectd_run_dir")
    $share_dir      = lookup("collectd_share_dir")
    $upstream       = lookup("collectd_upstream")
    $usr_dir        = lookup("collectd_usr_dir")
    $var_dir        = lookup("collectd_var_dir")
    $writes_per_sec = lookup("collectd_writes_per_second")
}
