class nginx::vars {
    $all_networks         = hiera_hash("vlan_database")
    $allow_privates       = hiera("apache_allow_privates")
    $cgi_socket           = hiera("nginx_cgi_socket")
    $csp_policies         = hiera("csp_policy_inventory")
    $csp_report           = hiera("csp_report")
    $csp_sources          = hiera("csp_sources")
    $conf_dir             = hiera("nginx_conf_dir")
    $do_letsencrypt       = hiera("apache_letsencrypt")
    $download             = hiera("download_cmd")
    $error_dir            = "$conf_dir/error"
    $hpkp_max_age         = hiera("hpkp_max_age")
    $hpkp_report          = hiera("hpkp_report")
    $keepalive            = hiera("nginx_keepalive_timeout")
    $listen_ports         = hiera("apache_listen_ports")
    $local_networks       = hiera("active_vlans")
    $log_dir              = hiera("nginx_log_dir")
    $log_group            = hiera("gid_adm")
    $log_user             = "root"
    $munin_conf_dir       = hiera("munin_conf_dir")
    $munin_monitored      = hiera("nginx_munin")
    $munin_probes         = hiera("nginx_munin_probes")
    $munin_service_name   = hiera("munin_node_service_name")
    $name_hash_bsize      = hiera("nginx_names_hash_bucket_size")
    $nginx_rsyslog        = hiera("nginx_rsyslog")
    $nginx_run_dir        = hiera("nginx_run_dir")
    $office_netids        = hiera("office_netids")
    $office_networks      = hiera("office_networks")
    $pki_master           = hiera("pki_master")
    $public_key_pins      = hiera("public_key_pins")
    $repo                 = hiera("puppet_http_repo")
    $runtime_group        = hiera("nginx_runtime_group")
    $runtime_user         = hiera("nginx_runtime_user")
    $rsyslog_conf_dir     = hiera("rsyslog_conf_dir")
    $rsyslog_service_name = hiera("rsyslog_service_name")
    $rsyslog_version      = hiera("rsyslog_version")
    $web_root             = hiera("apache_web_root")
    $with_cgi             = hiera("nginx_with_cgi")
    $with_collectd        = hiera("nginx_collectd")
    $worker_connections   = hiera("nginx_worker_connections")
    $worker_processes     = hiera("nginx_worker_processes")

    if ($nginx_rsyslog) {
	$rotate = 7
    } else {
	$rotate = 56
    }
}
