#!/bin/sh

awk '/[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*/{print $4}' /var/log/unbound.log |
    sort -n | awk '
	BEG {
	    ref="";
	    c=0;
	} {
	    if (ref == $0) {
		c = c + 1
	    } else {
		if (ref != "") {
		    print c " " ref
		}
		ref = $0;
		c=1;
	    }
	} END {
	    print c " " ref
	}' | sort -rn

exit 0
