#!/bin/sh

if test -z "$1"; then
    src=0.0.0.0/0
else
    src=$1
fi

if test -z "$2"; then
    dst=0.0.0.0/0
else
    dst=$2
fi

if test "$src" = "$dst"; then
    echo "PEBKAC" >&2
    exit 1
fi

if test `id -u` -ne 0; then
    /usr/bin/sudo /sbin/pfctl -k $src -k $dst
    /usr/bin/sudo /sbin/pfctl -k $dst -k $src
    /usr/bin/sudo /sbin/pfctl -K $src -K $dst
    /usr/bin/sudo /sbin/pfctl -K $dst -K $src
else
    /sbin/pfctl -k $src -k $dst
    /sbin/pfctl -k $dst -k $src
    /sbin/pfctl -K $src -K $dst
    /sbin/pfctl -K $dst -K $src
fi

exit 0
